from __future__ import annotations

from typing import Any


def _normalize_text(value: Any) -> str | None:
    if not isinstance(value, str):
        return None
    cleaned = value.strip().lower()
    return cleaned or None


DESTINATION_ALIASES: dict[str, str] = {
    "mount kenya": "mt kenya",
    "mt kenya": "mt kenya",
    "masai mara": "maasai mara",
    "mara": "maasai mara",
    "lake naivasha": "naivasha",
    "lake nakuru": "nakuru",
    "ngare dare": "ngare ndare",
}

DESTINATION_PROFILES: dict[str, dict[str, Any]] = {
    "diani": {
        "destination_type": "coastal",
        "activity_bias": ["beach", "water", "relaxation"],
        "transport_bias": "road_or_air_connection",
        "accommodation_bias": "resort_or_beachfront",
        "pace_bias": "relaxed",
        "risk_flags": ["heat", "weekend_crowds"],
    },
    "mombasa": {
        "destination_type": "coastal",
        "activity_bias": ["beach", "water", "culture"],
        "transport_bias": "road_or_air_connection",
        "accommodation_bias": "resort_or_city_hotel",
        "pace_bias": "balanced",
        "risk_flags": ["traffic", "heat"],
    },
    "watamu": {
        "destination_type": "coastal",
        "activity_bias": ["beach", "water", "relaxation"],
        "transport_bias": "road_or_air_connection",
        "accommodation_bias": "resort_or_beachfront",
        "pace_bias": "relaxed",
        "risk_flags": ["heat"],
    },
    "malindi": {
        "destination_type": "coastal",
        "activity_bias": ["beach", "water", "culture"],
        "transport_bias": "road_or_air_connection",
        "accommodation_bias": "resort_or_beachfront",
        "pace_bias": "balanced",
        "risk_flags": ["heat"],
    },
    "lamu": {
        "destination_type": "coastal",
        "activity_bias": ["beach", "culture", "relaxation"],
        "transport_bias": "air_or_boat_connection",
        "accommodation_bias": "boutique_or_beachfront",
        "pace_bias": "slow",
        "risk_flags": ["boat_transfer", "heat"],
    },
    "kilifi": {
        "destination_type": "coastal",
        "activity_bias": ["beach", "water", "relaxation"],
        "transport_bias": "road_connection",
        "accommodation_bias": "resort_or_beachfront",
        "pace_bias": "relaxed",
        "risk_flags": ["heat"],
    },
    "vipingo": {
        "destination_type": "coastal",
        "activity_bias": ["beach", "relaxation", "scenic"],
        "transport_bias": "road_connection",
        "accommodation_bias": "villa_or_resort",
        "pace_bias": "relaxed",
        "risk_flags": ["heat"],
    },
    "tiwi": {
        "destination_type": "coastal",
        "activity_bias": ["beach", "water", "quiet"],
        "transport_bias": "road_connection",
        "accommodation_bias": "beachfront",
        "pace_bias": "slow",
        "risk_flags": ["heat"],
    },
    "nyali": {
        "destination_type": "coastal",
        "activity_bias": ["beach", "water", "urban"],
        "transport_bias": "road_connection",
        "accommodation_bias": "resort_or_city_hotel",
        "pace_bias": "balanced",
        "risk_flags": ["traffic", "heat"],
    },
    "shanzu": {
        "destination_type": "coastal",
        "activity_bias": ["beach", "water", "relaxation"],
        "transport_bias": "road_connection",
        "accommodation_bias": "resort_or_beachfront",
        "pace_bias": "relaxed",
        "risk_flags": ["heat"],
    },
    "bamburi": {
        "destination_type": "coastal",
        "activity_bias": ["beach", "water", "urban"],
        "transport_bias": "road_connection",
        "accommodation_bias": "resort_or_city_hotel",
        "pace_bias": "balanced",
        "risk_flags": ["traffic", "heat"],
    },
    "mtwapa": {
        "destination_type": "coastal",
        "activity_bias": ["beach", "water", "urban"],
        "transport_bias": "road_connection",
        "accommodation_bias": "hotel_or_apartment",
        "pace_bias": "balanced",
        "risk_flags": ["traffic", "heat"],
    },
    "ukunda": {
        "destination_type": "coastal",
        "activity_bias": ["beach", "water", "relaxation"],
        "transport_bias": "road_or_air_connection",
        "accommodation_bias": "resort_or_beachfront",
        "pace_bias": "relaxed",
        "risk_flags": ["heat"],
    },
    "mt kenya": {
        "destination_type": "mountain",
        "activity_bias": ["hiking", "nature", "outdoor"],
        "transport_bias": "road_transfer",
        "accommodation_bias": "lodge_or_cabin",
        "pace_bias": "active",
        "risk_flags": ["altitude", "cold_nights"],
    },
    "aberdare": {
        "destination_type": "mountain",
        "activity_bias": ["hiking", "nature", "outdoor"],
        "transport_bias": "road_transfer",
        "accommodation_bias": "lodge_or_cabin",
        "pace_bias": "active",
        "risk_flags": ["cold_nights", "rain"],
    },
    "aberdares": {
        "destination_type": "mountain",
        "activity_bias": ["hiking", "nature", "outdoor"],
        "transport_bias": "road_transfer",
        "accommodation_bias": "lodge_or_cabin",
        "pace_bias": "active",
        "risk_flags": ["cold_nights", "rain"],
    },
    "longonot": {
        "destination_type": "mountain",
        "activity_bias": ["hiking", "nature", "outdoor"],
        "transport_bias": "road_transfer",
        "accommodation_bias": "camp_or_lodge",
        "pace_bias": "active",
        "risk_flags": ["steep_trails", "heat"],
    },
    "mt longonot": {
        "destination_type": "mountain",
        "activity_bias": ["hiking", "nature", "outdoor"],
        "transport_bias": "road_transfer",
        "accommodation_bias": "camp_or_lodge",
        "pace_bias": "active",
        "risk_flags": ["steep_trails", "heat"],
    },
    "suswa": {
        "destination_type": "mountain",
        "activity_bias": ["hiking", "nature", "outdoor"],
        "transport_bias": "road_transfer",
        "accommodation_bias": "camp_or_lodge",
        "pace_bias": "active",
        "risk_flags": ["rough_access", "heat"],
    },
    "mt suswa": {
        "destination_type": "mountain",
        "activity_bias": ["hiking", "nature", "outdoor"],
        "transport_bias": "road_transfer",
        "accommodation_bias": "camp_or_lodge",
        "pace_bias": "active",
        "risk_flags": ["rough_access", "heat"],
    },
    "ngong hills": {
        "destination_type": "mountain",
        "activity_bias": ["hiking", "nature", "outdoor"],
        "transport_bias": "road_transfer",
        "accommodation_bias": "day_trip_or_lodge",
        "pace_bias": "active",
        "risk_flags": ["wind", "exposure"],
    },
    "mt elgon": {
        "destination_type": "mountain",
        "activity_bias": ["hiking", "nature", "outdoor"],
        "transport_bias": "road_transfer",
        "accommodation_bias": "lodge_or_cabin",
        "pace_bias": "active",
        "risk_flags": ["altitude", "distance"],
    },
    "cherangani": {
        "destination_type": "mountain",
        "activity_bias": ["hiking", "nature", "outdoor"],
        "transport_bias": "road_transfer",
        "accommodation_bias": "camp_or_lodge",
        "pace_bias": "active",
        "risk_flags": ["distance", "cold_nights"],
    },
    "nairobi": {
        "destination_type": "city",
        "activity_bias": ["urban", "dining", "culture", "logistics"],
        "transport_bias": "urban_road_transfer",
        "accommodation_bias": "city_hotel",
        "pace_bias": "fast",
        "risk_flags": ["traffic"],
    },
    "kisumu": {
        "destination_type": "city",
        "activity_bias": ["urban", "dining", "culture", "logistics"],
        "transport_bias": "urban_road_transfer",
        "accommodation_bias": "city_hotel",
        "pace_bias": "balanced",
        "risk_flags": ["traffic"],
    },
    "nakuru": {
        "destination_type": "city",
        "activity_bias": ["urban", "dining", "culture", "logistics"],
        "transport_bias": "urban_road_transfer",
        "accommodation_bias": "city_hotel",
        "pace_bias": "balanced",
        "risk_flags": ["traffic"],
    },
    "eldoret": {
        "destination_type": "city",
        "activity_bias": ["urban", "dining", "culture", "logistics"],
        "transport_bias": "urban_road_transfer",
        "accommodation_bias": "city_hotel",
        "pace_bias": "balanced",
        "risk_flags": [],
    },
    "thika": {
        "destination_type": "city",
        "activity_bias": ["urban", "dining", "culture", "logistics"],
        "transport_bias": "urban_road_transfer",
        "accommodation_bias": "city_hotel",
        "pace_bias": "balanced",
        "risk_flags": ["traffic"],
    },
    "nyeri": {
        "destination_type": "city",
        "activity_bias": ["urban", "culture", "logistics"],
        "transport_bias": "urban_road_transfer",
        "accommodation_bias": "city_hotel",
        "pace_bias": "balanced",
        "risk_flags": [],
    },
    "meru": {
        "destination_type": "city",
        "activity_bias": ["urban", "culture", "logistics"],
        "transport_bias": "urban_road_transfer",
        "accommodation_bias": "city_hotel",
        "pace_bias": "balanced",
        "risk_flags": [],
    },
    "nanyuki": {
        "destination_type": "city",
        "activity_bias": ["urban", "dining", "logistics"],
        "transport_bias": "urban_road_transfer",
        "accommodation_bias": "city_hotel",
        "pace_bias": "balanced",
        "risk_flags": [],
    },
    "kitale": {
        "destination_type": "city",
        "activity_bias": ["urban", "dining", "logistics"],
        "transport_bias": "urban_road_transfer",
        "accommodation_bias": "city_hotel",
        "pace_bias": "balanced",
        "risk_flags": [],
    },
    "maasai mara": {
        "destination_type": "safari",
        "activity_bias": ["wildlife", "game_drive", "photography"],
        "transport_bias": "airstrip_or_4x4",
        "accommodation_bias": "camp_or_lodge",
        "pace_bias": "early_start",
        "risk_flags": ["distance", "rough_access"],
    },
    "amboseli": {
        "destination_type": "safari",
        "activity_bias": ["wildlife", "game_drive", "photography"],
        "transport_bias": "road_or_4x4",
        "accommodation_bias": "camp_or_lodge",
        "pace_bias": "early_start",
        "risk_flags": ["dust", "distance"],
    },
    "tsavo": {
        "destination_type": "safari",
        "activity_bias": ["wildlife", "game_drive", "photography"],
        "transport_bias": "road_or_4x4",
        "accommodation_bias": "camp_or_lodge",
        "pace_bias": "early_start",
        "risk_flags": ["distance", "heat"],
    },
    "tsavo east": {
        "destination_type": "safari",
        "activity_bias": ["wildlife", "game_drive", "photography"],
        "transport_bias": "road_or_4x4",
        "accommodation_bias": "camp_or_lodge",
        "pace_bias": "early_start",
        "risk_flags": ["distance", "heat"],
    },
    "tsavo west": {
        "destination_type": "safari",
        "activity_bias": ["wildlife", "game_drive", "photography"],
        "transport_bias": "road_or_4x4",
        "accommodation_bias": "camp_or_lodge",
        "pace_bias": "early_start",
        "risk_flags": ["distance", "heat"],
    },
    "samburu": {
        "destination_type": "safari",
        "activity_bias": ["wildlife", "game_drive", "photography"],
        "transport_bias": "airstrip_or_4x4",
        "accommodation_bias": "camp_or_lodge",
        "pace_bias": "early_start",
        "risk_flags": ["distance", "heat"],
    },
    "shaba": {
        "destination_type": "safari",
        "activity_bias": ["wildlife", "game_drive", "photography"],
        "transport_bias": "airstrip_or_4x4",
        "accommodation_bias": "camp_or_lodge",
        "pace_bias": "early_start",
        "risk_flags": ["distance", "heat"],
    },
    "meru national park": {
        "destination_type": "safari",
        "activity_bias": ["wildlife", "game_drive", "photography"],
        "transport_bias": "road_or_4x4",
        "accommodation_bias": "camp_or_lodge",
        "pace_bias": "early_start",
        "risk_flags": ["distance", "rough_access"],
    },
    "nairobi national park": {
        "destination_type": "safari",
        "activity_bias": ["wildlife", "game_drive", "photography"],
        "transport_bias": "urban_road_transfer",
        "accommodation_bias": "city_hotel",
        "pace_bias": "balanced",
        "risk_flags": ["traffic"],
    },
    "ol pejeta": {
        "destination_type": "safari",
        "activity_bias": ["wildlife", "game_drive", "photography"],
        "transport_bias": "road_or_4x4",
        "accommodation_bias": "camp_or_lodge",
        "pace_bias": "early_start",
        "risk_flags": ["distance"],
    },
    "solio": {
        "destination_type": "safari",
        "activity_bias": ["wildlife", "game_drive", "photography"],
        "transport_bias": "road_or_4x4",
        "accommodation_bias": "lodge",
        "pace_bias": "balanced",
        "risk_flags": ["distance"],
    },
    "lake nakuru national park": {
        "destination_type": "safari",
        "activity_bias": ["wildlife", "game_drive", "photography"],
        "transport_bias": "road_or_4x4",
        "accommodation_bias": "lodge",
        "pace_bias": "balanced",
        "risk_flags": ["park_hours"],
    },
    "naivasha": {
        "destination_type": "lake",
        "activity_bias": ["boat", "nature", "relaxation"],
        "transport_bias": "road_transfer",
        "accommodation_bias": "lodge_or_lakeside",
        "pace_bias": "relaxed",
        "risk_flags": ["weekend_crowds"],
    },
    "lake victoria": {
        "destination_type": "lake",
        "activity_bias": ["boat", "nature", "relaxation"],
        "transport_bias": "road_or_air_connection",
        "accommodation_bias": "hotel_or_lakeside",
        "pace_bias": "balanced",
        "risk_flags": ["weather_exposure"],
    },
    "baringo": {
        "destination_type": "lake",
        "activity_bias": ["boat", "nature", "relaxation"],
        "transport_bias": "road_transfer",
        "accommodation_bias": "lodge_or_lakeside",
        "pace_bias": "relaxed",
        "risk_flags": ["distance", "heat"],
    },
    "elementaita": {
        "destination_type": "lake",
        "activity_bias": ["nature", "relaxation", "scenic"],
        "transport_bias": "road_transfer",
        "accommodation_bias": "lodge_or_lakeside",
        "pace_bias": "relaxed",
        "risk_flags": [],
    },
    "bogoria": {
        "destination_type": "lake",
        "activity_bias": ["nature", "scenic", "relaxation"],
        "transport_bias": "road_transfer",
        "accommodation_bias": "lodge",
        "pace_bias": "balanced",
        "risk_flags": ["heat", "distance"],
    },
    "karura": {
        "destination_type": "forest",
        "activity_bias": ["trail", "nature", "quiet"],
        "transport_bias": "urban_road_transfer",
        "accommodation_bias": "day_trip_or_city_hotel",
        "pace_bias": "slow",
        "risk_flags": [],
    },
    "karura forest": {
        "destination_type": "forest",
        "activity_bias": ["trail", "nature", "quiet"],
        "transport_bias": "urban_road_transfer",
        "accommodation_bias": "day_trip_or_city_hotel",
        "pace_bias": "slow",
        "risk_flags": [],
    },
    "arabuko sokoke": {
        "destination_type": "forest",
        "activity_bias": ["trail", "nature", "quiet"],
        "transport_bias": "road_transfer",
        "accommodation_bias": "eco_lodge",
        "pace_bias": "slow",
        "risk_flags": ["heat"],
    },
    "kakamega forest": {
        "destination_type": "forest",
        "activity_bias": ["trail", "nature", "quiet"],
        "transport_bias": "road_transfer",
        "accommodation_bias": "eco_lodge",
        "pace_bias": "slow",
        "risk_flags": ["rain"],
    },
    "ngare ndare": {
        "destination_type": "forest",
        "activity_bias": ["trail", "nature", "quiet"],
        "transport_bias": "road_transfer",
        "accommodation_bias": "camp_or_lodge",
        "pace_bias": "balanced",
        "risk_flags": ["distance"],
    },
    "aberdare forest": {
        "destination_type": "forest",
        "activity_bias": ["trail", "nature", "quiet"],
        "transport_bias": "road_transfer",
        "accommodation_bias": "lodge_or_cabin",
        "pace_bias": "balanced",
        "risk_flags": ["rain", "cold_nights"],
    },
    "isiolo": {
        "destination_type": "arid",
        "activity_bias": ["rugged", "remote", "scenic"],
        "transport_bias": "road_or_4x4",
        "accommodation_bias": "basic_lodge",
        "pace_bias": "steady",
        "risk_flags": ["heat", "distance"],
    },
    "marsabit": {
        "destination_type": "arid",
        "activity_bias": ["rugged", "remote", "scenic"],
        "transport_bias": "road_or_4x4",
        "accommodation_bias": "basic_lodge",
        "pace_bias": "steady",
        "risk_flags": ["heat", "distance"],
    },
    "turkana": {
        "destination_type": "arid",
        "activity_bias": ["rugged", "remote", "scenic"],
        "transport_bias": "road_or_4x4",
        "accommodation_bias": "basic_lodge",
        "pace_bias": "steady",
        "risk_flags": ["heat", "distance"],
    },
    "lodwar": {
        "destination_type": "arid",
        "activity_bias": ["rugged", "remote", "scenic"],
        "transport_bias": "road_or_4x4",
        "accommodation_bias": "basic_lodge",
        "pace_bias": "steady",
        "risk_flags": ["heat", "distance"],
    },
    "chalbi": {
        "destination_type": "arid",
        "activity_bias": ["rugged", "remote", "scenic"],
        "transport_bias": "4x4_required",
        "accommodation_bias": "camp",
        "pace_bias": "steady",
        "risk_flags": ["heat", "remote_access"],
    },
    "chalbi desert": {
        "destination_type": "arid",
        "activity_bias": ["rugged", "remote", "scenic"],
        "transport_bias": "4x4_required",
        "accommodation_bias": "camp",
        "pace_bias": "steady",
        "risk_flags": ["heat", "remote_access"],
    },
}


def normalize_destination_name(destination: str | None) -> str | None:
    cleaned = _normalize_text(destination)
    if not cleaned:
        return None
    return DESTINATION_ALIASES.get(cleaned, cleaned)


def get_destination_profile(destination: str | None) -> tuple[str | None, dict[str, Any] | None]:
    resolved_destination = normalize_destination_name(destination)
    profile = DESTINATION_PROFILES.get(resolved_destination)

    if not profile and resolved_destination:
        for key in DESTINATION_PROFILES:
            if key in resolved_destination:
                return key, DESTINATION_PROFILES[key]

    return resolved_destination, profile
